# Generated by Django 5.1.1 on 2025-11-12 01:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pulmora_Maps', '0003_comment_likes_alter_comment_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏆', max_length=50)),
                ('retos_requeridos', models.IntegerField()),
                ('color', models.CharField(default='#4caf50', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Recompensas',
                'ordering': ['retos_requeridos'],
            },
        ),
        migrations.CreateModel(
            name='Retos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('permanente', 'Permanente'), ('temporal', 'Temporal')], default='permanente', max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('icono', models.CharField(default='🌱', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Retos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(default=django.utils.timezone.now)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pulmora_Maps.recompensa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recompensas de usuarios',
                'unique_together': {('usuario', 'recompensa')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_actual', models.IntegerField(default=0)),
                ('objetivo_total', models.IntegerField(default=1)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pulmora_Maps.retos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Retos de usuarios',
                'unique_together': {('usuario', 'reto')},
            },
        ),
    ]
