# Generated by Django 5.1.1 on 2025-11-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pulmora_Maps', '0004_recompensa_retos_usuariorecompensa_usuarioreto'),
    ]

    operations = [
        migrations.AddField(
            model_name='retos',
            name='objetivo_sugerido',
            field=models.IntegerField(default=10),
        ),
    ]
